export const GET_AIRPORT_REQUEST = "GET_AIRPORT_REQUEST"
export const GET_AIRPORT_SUCCESS = "GET_AIRPORT_SUCCESS"
export const GET_AIRPORT_FAIL = "GET_AIRPORT_FAIL"

export const GET_HOTELS_REQUEST = "GET_HOTELS_REQUEST"
export const GET_HOTELS_SUCCESS = "GET_HOTELS_SUCCESS"
export const GET_HOTELS_FAIL = "GET_HOTELS_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"