export const TRANSFER_PLACE_REQUEST = "TRANSFER_PLACE_REQUEST"
export const TRANSFER_PLACE_SUCCESS = "TRANSFER_PLACE_SUCCESS"
export const TRANSFER_PLACE_FAIL = "TRANSFER_PLACE_FAIL"

export const TRANSFER_RESULT_REQUEST = "TRANSFER_RESULT_REQUEST"
export const TRANSFER_RESULT_SUCCESS = "TRANSFER_RESULT_SUCCESS"
export const TRANSFER_RESULT_FAIL = "TRANSFER_RESULT_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"